[FE1] - Syntactic Feature Extraction #9
sea-lab-wm/complexity-verification-project pull request #21
Opened 2023-09-11 21:20 UTC by zeesoolee

Re-forked and only updated files for my implementation. The only files I should have updated are:
FeatureExtractorTest.java
Features.java
Parser.java
SyntacticFeatureExtractor.java
feature_data.csv

2023-09-11 21:47 UTC, zeesoolee commented
How I calculated my new features:

All averages: counts the total number of each element and divides it by the loc.

MaxLineLength, MaxIndentationLength: It compares the current line/indentation length to the max line/indentation length

Notes:
 - Indentation length iterates through each line character by character, counting spaces and tabs until it reaches a non-space, non-tab character.
 - A blank line is considered once the line is trimmed. If the line is then declared empty, the blank line counter increases by 1 (if false then it moves on to check the following line).

2023-09-12 15:29 UTC, NGimhana requested changes
@zeesoolee

2023-09-12 15:29 UTC, NGimhana commented on ml_model/src/main/java/edu/wm/sealab/featureextraction/SyntacticFeatureExtractor.java
> +    //indentation length
Describe explicitly how indentation length calculation logic

2023-09-12 15:29 UTC, NGimhana commented on ml_model/src/main/java/edu/wm/sealab/featureextraction/SyntacticFeatureExtractor.java
> +    //average length in each line
How is this length calculated? Explicitly describe.

2023-09-12 15:29 UTC, NGimhana commented on ml_model/src/main/java/edu/wm/sealab/featureextraction/SyntacticFeatureExtractor.java
> +    //get the number of lines of code
Use LOC data from the loc_data.csv instead of this.

2023-09-12 15:29 UTC, NGimhana commented on ml_model/src/test/java/edu/wm/sealab/featureextraction/FeatureExtractorTest.java
Add tests for FeatureExtractorTestMultiple.java as well

2023-09-18 22:46 UTC, NGimhana commented on ml_model/src/main/java/edu/wm/sealab/featureextraction/Features.java
> +  private float avgLength = 0.0f;
change to avgLineLength

2023-09-18 22:46 UTC, NGimhana commented on ml_model/src/main/java/edu/wm/sealab/featureextraction/Features.java
> +  private int maxLength = 0;
maxLineLength

2023-09-27 14:42 UTC, NGimhana commented on ml_model/src/main/java/edu/wm/sealab/featureextraction/Parser.java
> +                double avgBlankLines = features.getTotalBlankLines() / entryNumLinesOfCode;
For this I suggest instead of entryNumLinesOfCode, use blank_lines+entryNumLinesOfCode

2023-09-27 14:43 UTC, NGimhana commented on ml_model/src/main/java/edu/wm/sealab/featureextraction/SyntacticFeatureExtractor.java
> +    int loc = lines.length;
are we still using loc? I thought we agreed to use loc_data.csv.

2023-10-10 13:53 UTC, NGimhana commented
@zeesoolee cannot merge your PR due to merge conflicts. Could you please fix those?

2023-10-15 05:16 UTC, merged